In [1]:
import pandas as pd
import numpy as np
import nltk
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [2]:
dataset=pd.read_csv('spam.csv',encoding='latin-1')
dataset

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
sent=dataset['v2']
sent

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [4]:
labels=dataset['v1']
labels

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
labels=le.fit_transform(labels)
labels

array([0, 0, 1, ..., 0, 0, 0])

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))
features=cv.fit_transform(sent).toarray()
features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(features,labels,test_size=0.8,random_state=1)

In [8]:
from sklearn.naive_bayes import MultinomialNB
model_1=MultinomialNB()
model_1.fit(X_train,Y_train)
from sklearn.svm import SVC
model_2=SVC(kernel='linear')
model_2.fit(X_train,Y_train)
from sklearn.linear_model import LogisticRegression
model_3=LogisticRegression()
model_3.fit(X_train,Y_train)
from sklearn.tree import DecisionTreeClassifier
model_4=DecisionTreeClassifier()
model_4.fit(X_train,Y_train)

DecisionTreeClassifier()

In [9]:
pred_1=model_1.predict(X_test)
pred_2=model_2.predict(X_test)
pred_3=model_3.predict(X_test)
pred_4=model_4.predict(X_test)

In [10]:
import sklearn.metrics
print("Naive Bayes:\n ",sklearn.metrics.confusion_matrix(Y_test,pred_1))
print("SVC:\n ",sklearn.metrics.confusion_matrix(Y_test,pred_2))
print("Logistic Regression:\n ",sklearn.metrics.confusion_matrix(Y_test,pred_3))
print("Decision Tree:\n ",sklearn.metrics.confusion_matrix(Y_test,pred_4))

Naive Bayes:
  [[3664  188]
 [  53  553]]
SVC:
  [[3851    1]
 [ 362  244]]
Logistic Regression:
  [[3852    0]
 [ 428  178]]
Decision Tree:
  [[3827   25]
 [ 295  311]]


In [11]:
print("Naive Bayes: ",sklearn.metrics.accuracy_score(Y_test,pred_1))
print("SVC: ",sklearn.metrics.accuracy_score(Y_test,pred_2))
print("Logistic Regression: ",sklearn.metrics.accuracy_score(Y_test,pred_3))
print("Decision Tree: ",sklearn.metrics.accuracy_score(Y_test,pred_4))

Naive Bayes:  0.945939883355765
SVC:  0.9185733512786003
Logistic Regression:  0.9039928218932256
Decision Tree:  0.9282189322566173
